name: "Runs Flake 8 and comment o PR"
description: "Runs Flake 8 and comment o PR"

branding:
  color: blue
  icon: tag

inputs:
  personal_access_token:
    description: "Github Personal access token"
    required: true

  allowed_users:
    description: "Allowed users to generate auto release"
    required: false

  version_file:
    description: "File were the version is"
    required: false
    default: "VERSION"

  update_released_versions:
    description: "Update vX and vX.Y versions if a new vX.Y.Z version is released"
    required: false
    default: 'false'

runs:
  using: "docker"
  image: "Dockerfile"
