name: Flake 8
on:
  push:
    branches:
      - '*'
      - '**'
jobs:
  flake8:
    name: Flake 8
    runs-on: ubuntu-latest
    steps:
      - name: Run Flake 8
        uses: heitorpolidoro/flake8-with-PR-comments@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
