name: Flake 8
on:
  push:

jobs:
  flake8:
    name: Flake 8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "flake8-with-PR-comments"
      - name: Run Flake 8
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
